### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kenlunde** [tonton-pixel/Unihan-Definitions-Error-Report#1]
The following are my ideas for some of them:

U+3D37 㴷 = incessantly
U+4F3D 伽 = temple
U+57DD 埝 = protuberance
U+5A08 娈 = obedient
U+5F8A 徊 = hesitate
U+7BB4 箴 = warn, admonish
U+8B05 謅 = nonsense
U+8BCC 诌 = nonsense
U+8D4E 赎 = ransom
U+8DF8 跸 = clear street when emperor tours
U+8E55 蹕 = clear street when emperor tours
U+92D9 鋙 = discordant
U+94FB 铻 = discordant
U+97D9 韙 = propriety
U+97EA 韪 = propriety
U+22C55 𢱕 = pound
U+252D8 𥋘 = sweep

[Edited to make adjustments, after realizing that you specified only the words in question, and not the entire property value.]

**Comment by tonton-pixel** [comment]
Thanks! I can start updating some items from the list right now, but I may eventually have to wait until I know if I need to modify the existing file, and how. If the data file is available on GitHub, it would be a matter of forking and sending a pull request, I guess...

**Comment by kenlunde** [comment]
@tonton-pixel Others may chime in with suggestions, so give it some time. I will also continue to check. The best way to submit the corrections is either as a document with an attachment that includes only the suggested changes, sort of like the following for the first entry above (using tabs, of course), or via the [Contact Form](https://unicode.org/reporting.html) in the same format:

U+3D37 kDefinition flood

**Comment by kenlunde** [comment]
@tonton-pixel I just made adjustments. See my edit note above.

**Comment by kenlunde** [comment]
Here are some additional suggestions:

U+356F 㕯 = shouting
U+3A62 㩢 = judge [also change "weight" to "weigh"]
U+3ABC 㪼 = drag
U+3E21 㸡 = cross
U+42AC 䊬 = antipyretic
U+463D 䘽 = article
U+46E2 䛢 = silly
U+46EF 䛯 = speaking [also change "reasonable to" to "reason for"]
U+484D 䡍 = wheel
U+4933 䤳 = mirror

**Comment by kenlunde** [comment]
The above suggestions should take care of everything that had a question mark.

**Comment by Tsengtsz** [comment]
They all look correct to me, but I'm still checking.

**Comment by tonton-pixel** [comment]
I just updated the main `README.md` file with the current suggestions, adding the Unihan character after each code point.
I also committed a new document `Unihan_Readings_kDefinition-Corrected.txt`with the suggested changes, in the same format than the original document `Unihan_Readings.txt`, but containing only the modified lines.

**Comment by tonton-pixel** [comment]
This error report has been successfully submitted and registered as the UTC document [L2/19-257](http://www.unicode.org/L2/L2019/19257-unihan-error-rept.pdf).
Thanks to everyone involved for so valuable help and kind consideration.

**Comment by kenlunde** [comment]
Just FYI, the error report, [L2/19-257](https://www.unicode.org/L2/L2019/19257-unihan-error-rept.pdf), was discussed yesterday morning at UTC160, and was accepted. The Unihan Database for Unicode Version 13.0 will reflect these adjustments. Thank you.
